<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $timestamp = now();

        DB::table('master_aset')->upsert([
            [
                'a_code' => 'AST-001',
                'a_name' => 'Laptop Lenovo ThinkPad',
                'a_type' => 'Laptop',
                'a_desc' => 'Laptop kerja untuk kebutuhan operasional dan administrasi.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-002',
                'a_name' => 'Laptop ASUS VivoBook',
                'a_type' => 'Laptop',
                'a_desc' => 'Laptop kerja untuk kegiatan lapangan dan presentasi.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-003',
                'a_name' => 'Monitor Dell 24 Inch',
                'a_type' => 'Monitor',
                'a_desc' => 'Monitor eksternal untuk workstation kantor.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-004',
                'a_name' => 'Proyektor Epson',
                'a_type' => 'Proyektor',
                'a_desc' => 'Proyektor untuk rapat dan kebutuhan presentasi.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-005',
                'a_name' => 'Kamera Canon EOS',
                'a_type' => 'Kamera',
                'a_desc' => 'Kamera dokumentasi kegiatan internal dan eksternal.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-006',
                'a_name' => 'Tripod Kamera',
                'a_type' => 'Aksesori Kamera',
                'a_desc' => 'Tripod pendukung dokumentasi dan produksi konten.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-007',
                'a_name' => 'Printer Multifungsi',
                'a_type' => 'Printer',
                'a_desc' => 'Printer kantor dengan fungsi cetak, pindai, dan salin.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-008',
                'a_name' => 'Router Wi-Fi',
                'a_type' => 'Perangkat Jaringan',
                'a_desc' => 'Perangkat jaringan untuk konektivitas ruang kerja.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-009',
                'a_name' => 'Tablet Samsung Galaxy',
                'a_type' => 'Tablet',
                'a_desc' => 'Tablet untuk pendataan dan pemeriksaan aset di lapangan.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-010',
                'a_name' => 'Speaker Portable',
                'a_type' => 'Audio',
                'a_desc' => 'Speaker portabel untuk rapat dan kegiatan internal.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-011',
                'a_name' => 'Laptop MacBook Pro',
                'a_type' => 'Laptop',
                'a_desc' => 'Laptop performa tinggi untuk desain dan pengembangan.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-012',
                'a_name' => 'Monitor LG UltraWide 34 Inch',
                'a_type' => 'Monitor',
                'a_desc' => 'Monitor lebar untuk multitasking dan desain grafis.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-013',
                'a_name' => 'Proyektor BenQ',
                'a_type' => 'Proyektor',
                'a_desc' => 'Proyektor HD untuk ruang rapat besar.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-014',
                'a_name' => 'Kamera Sony Alpha',
                'a_type' => 'Kamera',
                'a_desc' => 'Kamera mirrorless untuk dokumentasi profesional.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-015',
                'a_name' => 'Gimbal DJI Ronin',
                'a_type' => 'Aksesori Kamera',
                'a_desc' => 'Stabilizer kamera untuk video cinematic.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-016',
                'a_name' => 'Printer Canon ImageRunner',
                'a_type' => 'Printer',
                'a_desc' => 'Printer produksi volume tinggi untuk kantor.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-017',
                'a_name' => 'Switch Network 24 Port',
                'a_type' => 'Perangkat Jaringan',
                'a_desc' => 'Switch jaringan managed untuk infrastruktur kantor.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-018',
                'a_name' => 'iPad Pro 12.9',
                'a_type' => 'Tablet',
                'a_desc' => 'Tablet profesional untuk presentasi dan desain.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-019',
                'a_name' => 'Sound System JBL',
                'a_type' => 'Audio',
                'a_desc' => 'Sistem audio lengkap untuk aula dan event.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-020',
                'a_name' => 'Laptop Dell XPS',
                'a_type' => 'Laptop',
                'a_desc' => 'Laptop premium untuk eksekutif dan manajemen.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-021',
                'a_name' => 'Monitor Samsung Curved 27 Inch',
                'a_type' => 'Monitor',
                'a_desc' => 'Monitor curved untuk kenyamanan visual panjang.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-022',
                'a_name' => 'Proyektor Optoma 4K',
                'a_type' => 'Proyektor',
                'a_desc' => 'Proyektor 4K untuk presentasi detail tinggi.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-023',
                'a_name' => 'Drone DJI Mavic',
                'a_type' => 'Kamera',
                'a_desc' => 'Drone untuk pengambilan gambar udara dan survey.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-024',
                'a_name' => 'Lighting Kit Studio',
                'a_type' => 'Aksesori Kamera',
                'a_desc' => 'Peralatan pencahayaan studio untuk foto/video.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-025',
                'a_name' => 'Scanner Fujitsu',
                'a_type' => 'Printer',
                'a_desc' => 'Scanner dokumen kecepatan tinggi untuk arsip digital.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-026',
                'a_name' => 'Access Point Ubiquiti',
                'a_type' => 'Perangkat Jaringan',
                'a_desc' => 'Access point enterprise untuk coverage Wi-Fi luas.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-027',
                'a_name' => 'Microsoft Surface Pro',
                'a_type' => 'Tablet',
                'a_desc' => 'Tablet 2-in-1 untuk mobilitas dan produktivitas.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-028',
                'a_name' => 'Wireless Mic System',
                'a_type' => 'Audio',
                'a_desc' => 'Sistem mikrofon nirkabel untuk presentasi dan wawancara.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-029',
                'a_name' => 'Laptop HP EliteBook',
                'a_type' => 'Laptop',
                'a_desc' => 'Laptop bisnis dengan keamanan tingkat enterprise.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
            [
                'a_code' => 'AST-030',
                'a_name' => 'Monitor ASUS ProArt 32 Inch 4K',
                'a_type' => 'Monitor',
                'a_desc' => 'Monitor 4K kalibrasi warna untuk desain profesional.',
                'a_status' => 'Available',
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ],
        ], ['a_code'], ['a_name', 'a_type', 'a_desc', 'a_status', 'updated_at']);
    }
}
